//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXApplication2.Model.j_embuscado_cms
{

    public partial class analysis : XPCustomObject
    {
        string fOid;
        [Key]
        [Size(38)]
        public string Oid
        {
            get { return fOid; }
            set { SetPropertyValue<string>("Oid", ref fOid, value); }
        }
        string fDimensionPropertiesString;
        [Size(SizeAttribute.Unlimited)]
        public string DimensionPropertiesString
        {
            get { return fDimensionPropertiesString; }
            set { SetPropertyValue<string>("DimensionPropertiesString", ref fDimensionPropertiesString, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>("Name", ref fName, value); }
        }
        string fCriteria;
        [Size(SizeAttribute.Unlimited)]
        public string Criteria
        {
            get { return fCriteria; }
            set { SetPropertyValue<string>("Criteria", ref fCriteria, value); }
        }
        string fObjectTypeName;
        public string ObjectTypeName
        {
            get { return fObjectTypeName; }
            set { SetPropertyValue<string>("ObjectTypeName", ref fObjectTypeName, value); }
        }
        byte[] fChartSettingsContent;
        [Size(SizeAttribute.Unlimited)]
        public byte[] ChartSettingsContent
        {
            get { return fChartSettingsContent; }
            set { SetPropertyValue<byte[]>("ChartSettingsContent", ref fChartSettingsContent, value); }
        }
        byte[] fPivotGridSettingsContent;
        [Size(SizeAttribute.Unlimited)]
        public byte[] PivotGridSettingsContent
        {
            get { return fPivotGridSettingsContent; }
            set { SetPropertyValue<byte[]>("PivotGridSettingsContent", ref fPivotGridSettingsContent, value); }
        }
        public analysis(Session session) : base(session) { }
    }

}
