//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXApplication2.Model.j_embuscado_cms
{

    public partial class auditedobjectweakreference : XPLiteObject
    {
        string fOid;
        [Key]
        [Size(38)]
        public string Oid
        {
            get { return fOid; }
            set { SetPropertyValue<string>("Oid", ref fOid, value); }
        }
        string fGuidId;
        [Size(38)]
        public string GuidId
        {
            get { return fGuidId; }
            set { SetPropertyValue<string>("GuidId", ref fGuidId, value); }
        }
        int fIntId;
        public int IntId
        {
            get { return fIntId; }
            set { SetPropertyValue<int>("IntId", ref fIntId, value); }
        }
        string fDisplayName;
        [Size(250)]
        public string DisplayName
        {
            get { return fDisplayName; }
            set { SetPropertyValue<string>("DisplayName", ref fDisplayName, value); }
        }
        [Association(@"auditdataitempersistentReferencesauditedobjectweakreference")]
        public XPCollection<auditdataitempersistent> auditdataitempersistents { get { return GetCollection<auditdataitempersistent>("auditdataitempersistents"); } }
        public auditedobjectweakreference(Session session) : base(session) { }
    }

}
