//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXApplication2.Model.j_embuscado_cms
{

    public partial class auditdataitempersistent : XPCustomObject
    {
        string fOid;
        [Key]
        [Size(38)]
        public string Oid
        {
            get { return fOid; }
            set { SetPropertyValue<string>("Oid", ref fOid, value); }
        }
        string fUserName;
        [Indexed(Name = @"iUserName_AuditDataItemPersistent")]
        public string UserName
        {
            get { return fUserName; }
            set { SetPropertyValue<string>("UserName", ref fUserName, value); }
        }
        DateTime fModifiedOn;
        [Indexed(Name = @"iModifiedOn_AuditDataItemPersistent")]
        public DateTime ModifiedOn
        {
            get { return fModifiedOn; }
            set { SetPropertyValue<DateTime>("ModifiedOn", ref fModifiedOn, value); }
        }
        string fOperationType;
        [Indexed(Name = @"iOperationType_AuditDataItemPersistent")]
        public string OperationType
        {
            get { return fOperationType; }
            set { SetPropertyValue<string>("OperationType", ref fOperationType, value); }
        }
        string fDescription;
        [Size(SizeAttribute.Unlimited)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        auditedobjectweakreference fAuditedObject;
        [Size(38)]
        [Association(@"auditdataitempersistentReferencesauditedobjectweakreference")]
        public auditedobjectweakreference AuditedObject
        {
            get { return fAuditedObject; }
            set { SetPropertyValue<auditedobjectweakreference>("AuditedObject", ref fAuditedObject, value); }
        }
        string fOldObject;
        [Indexed(Name = @"iOldObject_AuditDataItemPersistent")]
        [Size(38)]
        public string OldObject
        {
            get { return fOldObject; }
            set { SetPropertyValue<string>("OldObject", ref fOldObject, value); }
        }
        string fNewObject;
        [Indexed(Name = @"iNewObject_AuditDataItemPersistent")]
        [Size(38)]
        public string NewObject
        {
            get { return fNewObject; }
            set { SetPropertyValue<string>("NewObject", ref fNewObject, value); }
        }
        string fOldValue;
        [Size(SizeAttribute.Unlimited)]
        public string OldValue
        {
            get { return fOldValue; }
            set { SetPropertyValue<string>("OldValue", ref fOldValue, value); }
        }
        string fNewValue;
        [Size(SizeAttribute.Unlimited)]
        public string NewValue
        {
            get { return fNewValue; }
            set { SetPropertyValue<string>("NewValue", ref fNewValue, value); }
        }
        string fPropertyName;
        public string PropertyName
        {
            get { return fPropertyName; }
            set { SetPropertyValue<string>("PropertyName", ref fPropertyName, value); }
        }
        public auditdataitempersistent(Session session) : base(session) { }
    }

}
