//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXApplication2.Model.j_embuscado_cms
{

    [Persistent(@"case")]
    public partial class case1 : XPObject
    {
        filedata fFile;
        [Size(38)]
        [Association(@"case1Referencesfiledata")]
        public filedata File
        {
            get { return fFile; }
            set { SetPropertyValue<filedata>("File", ref fFile, value); }
        }
        party fFirstParty;
        [Association(@"case1Referencesparty")]
        public party FirstParty
        {
            get { return fFirstParty; }
            set { SetPropertyValue<party>("FirstParty", ref fFirstParty, value); }
        }
        party fSecondParty;
        [Association(@"case1Referencesparty2")]
        public party SecondParty
        {
            get { return fSecondParty; }
            set { SetPropertyValue<party>("SecondParty", ref fSecondParty, value); }
        }
        string fCaseNo;
        public string CaseNo
        {
            get { return fCaseNo; }
            set { SetPropertyValue<string>("CaseNo", ref fCaseNo, value); }
        }
        type fType;
        [Association(@"case1Referencestype")]
        public type Type
        {
            get { return fType; }
            set { SetPropertyValue<type>("Type", ref fType, value); }
        }
        kind fKind;
        [Association(@"case1Referenceskind")]
        public kind Kind
        {
            get { return fKind; }
            set { SetPropertyValue<kind>("Kind", ref fKind, value); }
        }
        DateTime fFiled;
        public DateTime Filed
        {
            get { return fFiled; }
            set { SetPropertyValue<DateTime>("Filed", ref fFiled, value); }
        }
        DateTime fAssigned;
        public DateTime Assigned
        {
            get { return fAssigned; }
            set { SetPropertyValue<DateTime>("Assigned", ref fAssigned, value); }
        }
        status fStatus;
        [Association(@"case1Referencesstatus")]
        public status Status
        {
            get { return fStatus; }
            set { SetPropertyValue<status>("Status", ref fStatus, value); }
        }
        stage fStage;
        [Association(@"case1Referencesstage")]
        public stage Stage
        {
            get { return fStage; }
            set { SetPropertyValue<stage>("Stage", ref fStage, value); }
        }
        string fCalendar;
        public string Calendar
        {
            get { return fCalendar; }
            set { SetPropertyValue<string>("Calendar", ref fCalendar, value); }
        }
        call fCall;
        [Association(@"case1Referencescall")]
        public call Call
        {
            get { return fCall; }
            set { SetPropertyValue<call>("Call", ref fCall, value); }
        }
        DateTime fLastInvDate;
        public DateTime LastInvDate
        {
            get { return fLastInvDate; }
            set { SetPropertyValue<DateTime>("LastInvDate", ref fLastInvDate, value); }
        }
        flagged fFlag;
        [Association(@"case1Referencesflagged")]
        public flagged Flag
        {
            get { return fFlag; }
            set { SetPropertyValue<flagged>("Flag", ref fFlag, value); }
        }
        string fJurisdiction;
        public string Jurisdiction
        {
            get { return fJurisdiction; }
            set { SetPropertyValue<string>("Jurisdiction", ref fJurisdiction, value); }
        }
        ruleapplied fRuleApplied;
        [Association(@"case1Referencesruleapplied")]
        public ruleapplied RuleApplied
        {
            get { return fRuleApplied; }
            set { SetPropertyValue<ruleapplied>("RuleApplied", ref fRuleApplied, value); }
        }
        party fFirstPartyRep;
        [Association(@"case1Referencesparty1")]
        public party FirstPartyRep
        {
            get { return fFirstPartyRep; }
            set { SetPropertyValue<party>("FirstPartyRep", ref fFirstPartyRep, value); }
        }
        party fSecondPartyRep;
        [Association(@"case1Referencesparty3")]
        public party SecondPartyRep
        {
            get { return fSecondPartyRep; }
            set { SetPropertyValue<party>("SecondPartyRep", ref fSecondPartyRep, value); }
        }
        DateTime fDisposed;
        public DateTime Disposed
        {
            get { return fDisposed; }
            set { SetPropertyValue<DateTime>("Disposed", ref fDisposed, value); }
        }
        short fCount;
        public short Count
        {
            get { return fCount; }
            set { SetPropertyValue<short>("Count", ref fCount, value); }
        }
        [Association(@"casepartyReferencescase1")]
        public XPCollection<caseparty> caseparties { get { return GetCollection<caseparty>("caseparties"); } }
        [Association(@"docketReferencescase1")]
        public XPCollection<docket> dockets { get { return GetCollection<docket>("dockets"); } }
        [Association(@"documentfiledataReferencescase1")]
        public XPCollection<documentfiledata> documentfiledatas { get { return GetCollection<documentfiledata>("documentfiledatas"); } }
        [Association(@"noteReferencescase1")]
        public XPCollection<note> notes { get { return GetCollection<note>("notes"); } }
        public case1(Session session) : base(session) { }
    }

}
