//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXApplication2.Model.j_embuscado_cms
{

    public partial class caseparty : XPObject
    {
        string fCaseNo;
        public string CaseNo
        {
            get { return fCaseNo; }
            set { SetPropertyValue<string>("CaseNo", ref fCaseNo, value); }
        }
        int fParty;
        public int Party
        {
            get { return fParty; }
            set { SetPropertyValue<int>("Party", ref fParty, value); }
        }
        kind fKind;
        [Association(@"casepartyReferenceskind")]
        public kind Kind
        {
            get { return fKind; }
            set { SetPropertyValue<kind>("Kind", ref fKind, value); }
        }
        int fStanding;
        public int Standing
        {
            get { return fStanding; }
            set { SetPropertyValue<int>("Standing", ref fStanding, value); }
        }
        int fAttribute;
        public int Attribute
        {
            get { return fAttribute; }
            set { SetPropertyValue<int>("Attribute", ref fAttribute, value); }
        }
        case1 fCase;
        [Association(@"casepartyReferencescase1")]
        public case1 Case
        {
            get { return fCase; }
            set { SetPropertyValue<case1>("Case", ref fCase, value); }
        }
        DateTime fDate;
        public DateTime Date
        {
            get { return fDate; }
            set { SetPropertyValue<DateTime>("Date", ref fDate, value); }
        }
        string fRemarks;
        public string Remarks
        {
            get { return fRemarks; }
            set { SetPropertyValue<string>("Remarks", ref fRemarks, value); }
        }
        public caseparty(Session session) : base(session) { }
    }

}
