//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXApplication2.Model.j_embuscado_cms
{

    public partial class docket : XPObject
    {
        DateTime fDate;
        public DateTime Date
        {
            get { return fDate; }
            set { SetPropertyValue<DateTime>("Date", ref fDate, value); }
        }
        string fDescription;
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        string fExpediente;
        [Size(SizeAttribute.Unlimited)]
        public string Expediente
        {
            get { return fExpediente; }
            set { SetPropertyValue<string>("Expediente", ref fExpediente, value); }
        }
        DateTime fResetTo;
        public DateTime ResetTo
        {
            get { return fResetTo; }
            set { SetPropertyValue<DateTime>("ResetTo", ref fResetTo, value); }
        }
        DateTime fDueDate;
        public DateTime DueDate
        {
            get { return fDueDate; }
            set { SetPropertyValue<DateTime>("DueDate", ref fDueDate, value); }
        }
        int fFlag;
        public int Flag
        {
            get { return fFlag; }
            set { SetPropertyValue<int>("Flag", ref fFlag, value); }
        }
        docketstatus fStatus;
        [Association(@"docketReferencesdocketstatus")]
        public docketstatus Status
        {
            get { return fStatus; }
            set { SetPropertyValue<docketstatus>("Status", ref fStatus, value); }
        }
        case1 fCase;
        [Association(@"docketReferencescase1")]
        public case1 Case
        {
            get { return fCase; }
            set { SetPropertyValue<case1>("Case", ref fCase, value); }
        }
        docketitem fItem;
        [Association(@"docketReferencesdocketitem")]
        public docketitem Item
        {
            get { return fItem; }
            set { SetPropertyValue<docketitem>("Item", ref fItem, value); }
        }
        time fResetTime;
        [Association(@"docketReferencestime")]
        public time ResetTime
        {
            get { return fResetTime; }
            set { SetPropertyValue<time>("ResetTime", ref fResetTime, value); }
        }
        [Association(@"appearanceReferencesdocket")]
        public XPCollection<appearance> appearances { get { return GetCollection<appearance>("appearances"); } }
        [Association(@"documentReferencesdocket")]
        public XPCollection<document> documents { get { return GetCollection<document>("documents"); } }
        public docket(Session session) : base(session) { }
    }

}
