//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXApplication2.Model.j_embuscado_cms
{

    public partial class documentfiledata : XPCustomObject
    {
        string fOid;
        [Key]
        [Size(38)]
        public string Oid
        {
            get { return fOid; }
            set { SetPropertyValue<string>("Oid", ref fOid, value); }
        }
        filedata fFile;
        [Size(38)]
        [Association(@"documentfiledataReferencesfiledata")]
        public filedata File
        {
            get { return fFile; }
            set { SetPropertyValue<filedata>("File", ref fFile, value); }
        }
        case1 fCase;
        [Association(@"documentfiledataReferencescase1")]
        public case1 Case
        {
            get { return fCase; }
            set { SetPropertyValue<case1>("Case", ref fCase, value); }
        }
        int fDocumentType;
        public int DocumentType
        {
            get { return fDocumentType; }
            set { SetPropertyValue<int>("DocumentType", ref fDocumentType, value); }
        }
        public documentfiledata(Session session) : base(session) { }
    }

}
