//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXApplication2.Model.j_embuscado_cms
{

    public partial class document : XPObject
    {
        byte[] fImage;
        [Size(SizeAttribute.Unlimited)]
        public byte[] Image
        {
            get { return fImage; }
            set { SetPropertyValue<byte[]>("Image", ref fImage, value); }
        }
        docket fDocket;
        [Association(@"documentReferencesdocket")]
        public docket Docket
        {
            get { return fDocket; }
            set { SetPropertyValue<docket>("Docket", ref fDocket, value); }
        }
        string fDocTitle;
        [Size(255)]
        public string DocTitle
        {
            get { return fDocTitle; }
            set { SetPropertyValue<string>("DocTitle", ref fDocTitle, value); }
        }
        string fDocType;
        [Size(5)]
        public string DocType
        {
            get { return fDocType; }
            set { SetPropertyValue<string>("DocType", ref fDocType, value); }
        }
        DateTime fDateCreated;
        public DateTime DateCreated
        {
            get { return fDateCreated; }
            set { SetPropertyValue<DateTime>("DateCreated", ref fDateCreated, value); }
        }
        DateTime fDateModified;
        public DateTime DateModified
        {
            get { return fDateModified; }
            set { SetPropertyValue<DateTime>("DateModified", ref fDateModified, value); }
        }
        public document(Session session) : base(session) { }
    }

}
