//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXApplication2.Model.j_embuscado_cms
{

    [Persistent(@"event")]
    public partial class event1 : XPCustomObject
    {
        string fOid;
        [Key]
        [Size(38)]
        public string Oid
        {
            get { return fOid; }
            set { SetPropertyValue<string>("Oid", ref fOid, value); }
        }
        string fResourceIds;
        [Size(SizeAttribute.Unlimited)]
        public string ResourceIds
        {
            get { return fResourceIds; }
            set { SetPropertyValue<string>("ResourceIds", ref fResourceIds, value); }
        }
        event1 fRecurrencePattern;
        [Size(38)]
        [Association(@"event1Referencesevent1")]
        public event1 RecurrencePattern
        {
            get { return fRecurrencePattern; }
            set { SetPropertyValue<event1>("RecurrencePattern", ref fRecurrencePattern, value); }
        }
        string fSubject;
        [Size(250)]
        public string Subject
        {
            get { return fSubject; }
            set { SetPropertyValue<string>("Subject", ref fSubject, value); }
        }
        string fDescription;
        [Size(SizeAttribute.Unlimited)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        DateTime fStartOn;
        [Indexed(Name = @"iStartOn_Event")]
        public DateTime StartOn
        {
            get { return fStartOn; }
            set { SetPropertyValue<DateTime>("StartOn", ref fStartOn, value); }
        }
        DateTime fEndOn;
        [Indexed(Name = @"iEndOn_Event")]
        public DateTime EndOn
        {
            get { return fEndOn; }
            set { SetPropertyValue<DateTime>("EndOn", ref fEndOn, value); }
        }
        byte fAllDay;
        public byte AllDay
        {
            get { return fAllDay; }
            set { SetPropertyValue<byte>("AllDay", ref fAllDay, value); }
        }
        string fLocation;
        public string Location
        {
            get { return fLocation; }
            set { SetPropertyValue<string>("Location", ref fLocation, value); }
        }
        int fLabel;
        public int Label
        {
            get { return fLabel; }
            set { SetPropertyValue<int>("Label", ref fLabel, value); }
        }
        int fStatus;
        public int Status
        {
            get { return fStatus; }
            set { SetPropertyValue<int>("Status", ref fStatus, value); }
        }
        int fType;
        public int Type
        {
            get { return fType; }
            set { SetPropertyValue<int>("Type", ref fType, value); }
        }
        double fRemindIn;
        public double RemindIn
        {
            get { return fRemindIn; }
            set { SetPropertyValue<double>("RemindIn", ref fRemindIn, value); }
        }
        string fReminderInfoXml;
        [Size(200)]
        public string ReminderInfoXml
        {
            get { return fReminderInfoXml; }
            set { SetPropertyValue<string>("ReminderInfoXml", ref fReminderInfoXml, value); }
        }
        DateTime fAlarmTime;
        public DateTime AlarmTime
        {
            get { return fAlarmTime; }
            set { SetPropertyValue<DateTime>("AlarmTime", ref fAlarmTime, value); }
        }
        byte fIsPostponed;
        public byte IsPostponed
        {
            get { return fIsPostponed; }
            set { SetPropertyValue<byte>("IsPostponed", ref fIsPostponed, value); }
        }
        string fRecurrenceInfoXml;
        [Size(SizeAttribute.Unlimited)]
        public string RecurrenceInfoXml
        {
            get { return fRecurrenceInfoXml; }
            set { SetPropertyValue<string>("RecurrenceInfoXml", ref fRecurrenceInfoXml, value); }
        }
        [Association(@"event1Referencesevent1")]
        public XPCollection<event1> event1Collection { get { return GetCollection<event1>("event1Collection"); } }
        [Association(@"resourceresources_eventeventsReferencesevent1")]
        public XPCollection<resourceresources_eventevents> resourceresources_eventeventss { get { return GetCollection<resourceresources_eventevents>("resourceresources_eventeventss"); } }
        public event1(Session session) : base(session) { }
    }

}
