//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXApplication2.Model.j_embuscado_cms
{

    public partial class filedata : XPCustomObject
    {
        string fOid;
        [Key]
        [Size(38)]
        public string Oid
        {
            get { return fOid; }
            set { SetPropertyValue<string>("Oid", ref fOid, value); }
        }
        int fsize;
        public int size
        {
            get { return fsize; }
            set { SetPropertyValue<int>("size", ref fsize, value); }
        }
        string fFileName;
        [Size(SizeAttribute.Unlimited)]
        public string FileName
        {
            get { return fFileName; }
            set { SetPropertyValue<string>("FileName", ref fFileName, value); }
        }
        byte[] fContent;
        [Size(SizeAttribute.Unlimited)]
        public byte[] Content
        {
            get { return fContent; }
            set { SetPropertyValue<byte[]>("Content", ref fContent, value); }
        }
        [Association(@"case1Referencesfiledata")]
        public XPCollection<case1> case1s { get { return GetCollection<case1>("case1s"); } }
        [Association(@"documentfiledataReferencesfiledata")]
        public XPCollection<documentfiledata> documentfiledatas { get { return GetCollection<documentfiledata>("documentfiledatas"); } }
        public filedata(Session session) : base(session) { }
    }

}
