//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXApplication2.Model.j_embuscado_cms
{

    public partial class kind : XPObject
    {
        string fDescription;
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        [Association(@"case1Referenceskind")]
        public XPCollection<case1> case1s { get { return GetCollection<case1>("case1s"); } }
        [Association(@"casepartyReferenceskind")]
        public XPCollection<caseparty> caseparties { get { return GetCollection<caseparty>("caseparties"); } }
        [Association(@"typetype_kindkindReferenceskind")]
        public XPCollection<typetype_kindkind> typetype_kindkinds { get { return GetCollection<typetype_kindkind>("typetype_kindkinds"); } }
        public kind(Session session) : base(session) { }
    }

}
