//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXApplication2.Model.j_embuscado_cms
{

    public partial class kpidefinition : XPCustomObject
    {
        string fOid;
        [Key]
        [Size(38)]
        public string Oid
        {
            get { return fOid; }
            set { SetPropertyValue<string>("Oid", ref fOid, value); }
        }
        string fTargetObjectType;
        public string TargetObjectType
        {
            get { return fTargetObjectType; }
            set { SetPropertyValue<string>("TargetObjectType", ref fTargetObjectType, value); }
        }
        DateTime fChanged1;
        [Persistent(@"Changed")]
        public DateTime Changed1
        {
            get { return fChanged1; }
            set { SetPropertyValue<DateTime>("Changed1", ref fChanged1, value); }
        }
        kpiinstance fKpiInstance;
        [Size(38)]
        [Association(@"kpidefinitionReferenceskpiinstance")]
        public kpiinstance KpiInstance
        {
            get { return fKpiInstance; }
            set { SetPropertyValue<kpiinstance>("KpiInstance", ref fKpiInstance, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>("Name", ref fName, value); }
        }
        byte fActive;
        public byte Active
        {
            get { return fActive; }
            set { SetPropertyValue<byte>("Active", ref fActive, value); }
        }
        string fCriteria;
        [Size(SizeAttribute.Unlimited)]
        public string Criteria
        {
            get { return fCriteria; }
            set { SetPropertyValue<string>("Criteria", ref fCriteria, value); }
        }
        string fExpression;
        [Size(SizeAttribute.Unlimited)]
        public string Expression
        {
            get { return fExpression; }
            set { SetPropertyValue<string>("Expression", ref fExpression, value); }
        }
        double fGreenZone;
        public double GreenZone
        {
            get { return fGreenZone; }
            set { SetPropertyValue<double>("GreenZone", ref fGreenZone, value); }
        }
        double fRedZone;
        public double RedZone
        {
            get { return fRedZone; }
            set { SetPropertyValue<double>("RedZone", ref fRedZone, value); }
        }
        string fRange;
        public string Range
        {
            get { return fRange; }
            set { SetPropertyValue<string>("Range", ref fRange, value); }
        }
        byte fCompare;
        public byte Compare
        {
            get { return fCompare; }
            set { SetPropertyValue<byte>("Compare", ref fCompare, value); }
        }
        string fRangeToCompare;
        public string RangeToCompare
        {
            get { return fRangeToCompare; }
            set { SetPropertyValue<string>("RangeToCompare", ref fRangeToCompare, value); }
        }
        int fMeasurementFrequency;
        public int MeasurementFrequency
        {
            get { return fMeasurementFrequency; }
            set { SetPropertyValue<int>("MeasurementFrequency", ref fMeasurementFrequency, value); }
        }
        int fMeasurementMode;
        public int MeasurementMode
        {
            get { return fMeasurementMode; }
            set { SetPropertyValue<int>("MeasurementMode", ref fMeasurementMode, value); }
        }
        int fDirection;
        public int Direction
        {
            get { return fDirection; }
            set { SetPropertyValue<int>("Direction", ref fDirection, value); }
        }
        DateTime fChangedOn;
        public DateTime ChangedOn
        {
            get { return fChangedOn; }
            set { SetPropertyValue<DateTime>("ChangedOn", ref fChangedOn, value); }
        }
        string fSuppressedSeries;
        public string SuppressedSeries
        {
            get { return fSuppressedSeries; }
            set { SetPropertyValue<string>("SuppressedSeries", ref fSuppressedSeries, value); }
        }
        byte fEnableCustomizeRepresentation;
        public byte EnableCustomizeRepresentation
        {
            get { return fEnableCustomizeRepresentation; }
            set { SetPropertyValue<byte>("EnableCustomizeRepresentation", ref fEnableCustomizeRepresentation, value); }
        }
        [Association(@"kpiinstanceReferenceskpidefinition")]
        public XPCollection<kpiinstance> kpiinstances { get { return GetCollection<kpiinstance>("kpiinstances"); } }
        public kpidefinition(Session session) : base(session) { }
    }

}
