//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXApplication2.Model.j_embuscado_cms
{

    public partial class kpihistoryitem : XPBaseObject
    {
        string fOid;
        [Key]
        [Size(38)]
        public string Oid
        {
            get { return fOid; }
            set { SetPropertyValue<string>("Oid", ref fOid, value); }
        }
        kpiinstance fKpiInstance;
        [Size(38)]
        [Association(@"kpihistoryitemReferenceskpiinstance")]
        public kpiinstance KpiInstance
        {
            get { return fKpiInstance; }
            set { SetPropertyValue<kpiinstance>("KpiInstance", ref fKpiInstance, value); }
        }
        DateTime fRangeStart;
        public DateTime RangeStart
        {
            get { return fRangeStart; }
            set { SetPropertyValue<DateTime>("RangeStart", ref fRangeStart, value); }
        }
        DateTime fRangeEnd;
        public DateTime RangeEnd
        {
            get { return fRangeEnd; }
            set { SetPropertyValue<DateTime>("RangeEnd", ref fRangeEnd, value); }
        }
        double fValue;
        public double Value
        {
            get { return fValue; }
            set { SetPropertyValue<double>("Value", ref fValue, value); }
        }
        public kpihistoryitem(Session session) : base(session) { }
    }

}
