//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXApplication2.Model.j_embuscado_cms
{

    public partial class kpiinstance : XPCustomObject
    {
        string fOid;
        [Key]
        [Size(38)]
        public string Oid
        {
            get { return fOid; }
            set { SetPropertyValue<string>("Oid", ref fOid, value); }
        }
        DateTime fForceMeasurementDateTime;
        public DateTime ForceMeasurementDateTime
        {
            get { return fForceMeasurementDateTime; }
            set { SetPropertyValue<DateTime>("ForceMeasurementDateTime", ref fForceMeasurementDateTime, value); }
        }
        kpidefinition fKpiDefinition;
        [Size(38)]
        [Association(@"kpiinstanceReferenceskpidefinition")]
        public kpidefinition KpiDefinition
        {
            get { return fKpiDefinition; }
            set { SetPropertyValue<kpidefinition>("KpiDefinition", ref fKpiDefinition, value); }
        }
        string fSettings;
        [Size(SizeAttribute.Unlimited)]
        public string Settings
        {
            get { return fSettings; }
            set { SetPropertyValue<string>("Settings", ref fSettings, value); }
        }
        [Association(@"kpidefinitionReferenceskpiinstance")]
        public XPCollection<kpidefinition> kpidefinitions { get { return GetCollection<kpidefinition>("kpidefinitions"); } }
        [Association(@"kpihistoryitemReferenceskpiinstance")]
        public XPCollection<kpihistoryitem> kpihistoryitems { get { return GetCollection<kpihistoryitem>("kpihistoryitems"); } }
        [Association(@"kpiscorecardscorecards_kpiinstanceindicatorsReferenceskpiinstance")]
        public XPCollection<kpiscorecardscorecards_kpiinstanceindicators> kpiscorecardscorecards_kpiinstanceindicatorss { get { return GetCollection<kpiscorecardscorecards_kpiinstanceindicators>("kpiscorecardscorecards_kpiinstanceindicatorss"); } }
        public kpiinstance(Session session) : base(session) { }
    }

}
