//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXApplication2.Model.j_embuscado_cms
{

    public partial class kpiscorecardscorecards_kpiinstanceindicators : XPObject
    {
        kpiinstance fIndicators;
        [Size(38)]
        [Association(@"kpiscorecardscorecards_kpiinstanceindicatorsReferenceskpiinstance")]
        public kpiinstance Indicators
        {
            get { return fIndicators; }
            set { SetPropertyValue<kpiinstance>("Indicators", ref fIndicators, value); }
        }
        kpiscorecard fScorecards;
        [Size(38)]
        [Association(@"kpiscorecardscorecards_kpiinstanceindicatorsReferenceskpiscorecard")]
        public kpiscorecard Scorecards
        {
            get { return fScorecards; }
            set { SetPropertyValue<kpiscorecard>("Scorecards", ref fScorecards, value); }
        }
        public kpiscorecardscorecards_kpiinstanceindicators(Session session) : base(session) { }
    }

}
