//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXApplication2.Model.j_embuscado_cms
{

    public partial class moduleinfo : XPBaseObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>("ID", ref fID, value); }
        }
        string fVersion;
        public string Version
        {
            get { return fVersion; }
            set { SetPropertyValue<string>("Version", ref fVersion, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>("Name", ref fName, value); }
        }
        string fAssemblyFileName;
        public string AssemblyFileName
        {
            get { return fAssemblyFileName; }
            set { SetPropertyValue<string>("AssemblyFileName", ref fAssemblyFileName, value); }
        }
        byte fIsMain;
        public byte IsMain
        {
            get { return fIsMain; }
            set { SetPropertyValue<byte>("IsMain", ref fIsMain, value); }
        }
        public moduleinfo(Session session) : base(session) { }
    }

}
