//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXApplication2.Model.j_embuscado_cms
{

    public partial class reportdatav2 : XPCustomObject
    {
        string fOid;
        [Key]
        [Size(38)]
        public string Oid
        {
            get { return fOid; }
            set { SetPropertyValue<string>("Oid", ref fOid, value); }
        }
        string fObjectTypeName;
        [Size(SizeAttribute.Unlimited)]
        public string ObjectTypeName
        {
            get { return fObjectTypeName; }
            set { SetPropertyValue<string>("ObjectTypeName", ref fObjectTypeName, value); }
        }
        byte[] fContent;
        [Size(SizeAttribute.Unlimited)]
        public byte[] Content
        {
            get { return fContent; }
            set { SetPropertyValue<byte[]>("Content", ref fContent, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>("Name", ref fName, value); }
        }
        string fParametersObjectTypeName;
        [Size(SizeAttribute.Unlimited)]
        public string ParametersObjectTypeName
        {
            get { return fParametersObjectTypeName; }
            set { SetPropertyValue<string>("ParametersObjectTypeName", ref fParametersObjectTypeName, value); }
        }
        byte fIsInplaceReport;
        public byte IsInplaceReport
        {
            get { return fIsInplaceReport; }
            set { SetPropertyValue<byte>("IsInplaceReport", ref fIsInplaceReport, value); }
        }
        string fPredefinedReportType;
        [Size(SizeAttribute.Unlimited)]
        public string PredefinedReportType
        {
            get { return fPredefinedReportType; }
            set { SetPropertyValue<string>("PredefinedReportType", ref fPredefinedReportType, value); }
        }
        public reportdatav2(Session session) : base(session) { }
    }

}
