//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXApplication2.Model.j_embuscado_cms
{

    public partial class resource : XPCustomObject
    {
        string fOid;
        [Key]
        [Size(38)]
        public string Oid
        {
            get { return fOid; }
            set { SetPropertyValue<string>("Oid", ref fOid, value); }
        }
        int fColor;
        public int Color
        {
            get { return fColor; }
            set { SetPropertyValue<int>("Color", ref fColor, value); }
        }
        string fCaption;
        public string Caption
        {
            get { return fCaption; }
            set { SetPropertyValue<string>("Caption", ref fCaption, value); }
        }
        [Association(@"resourceresources_eventeventsReferencesresource")]
        public XPCollection<resourceresources_eventevents> resourceresources_eventeventss { get { return GetCollection<resourceresources_eventevents>("resourceresources_eventeventss"); } }
        public resource(Session session) : base(session) { }
    }

}
