//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXApplication2.Model.j_embuscado_cms
{

    public partial class resourceresources_eventevents : XPObject
    {
        event1 fEvents;
        [Size(38)]
        [Association(@"resourceresources_eventeventsReferencesevent1")]
        public event1 Events
        {
            get { return fEvents; }
            set { SetPropertyValue<event1>("Events", ref fEvents, value); }
        }
        resource fResources;
        [Size(38)]
        [Association(@"resourceresources_eventeventsReferencesresource")]
        public resource Resources
        {
            get { return fResources; }
            set { SetPropertyValue<resource>("Resources", ref fResources, value); }
        }
        public resourceresources_eventevents(Session session) : base(session) { }
    }

}
