//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXApplication2.Model.j_embuscado_cms
{

    public partial class securitysystemrole : XPCustomObject
    {
        string fOid;
        [Key]
        [Size(38)]
        public string Oid
        {
            get { return fOid; }
            set { SetPropertyValue<string>("Oid", ref fOid, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>("Name", ref fName, value); }
        }
        byte fIsAdministrative;
        public byte IsAdministrative
        {
            get { return fIsAdministrative; }
            set { SetPropertyValue<byte>("IsAdministrative", ref fIsAdministrative, value); }
        }
        byte fCanEditModel;
        public byte CanEditModel
        {
            get { return fCanEditModel; }
            set { SetPropertyValue<byte>("CanEditModel", ref fCanEditModel, value); }
        }
        [Association(@"securitysystemroleparentroles_securitysystemrolechildrolesReferencessecuritysystemrole")]
        public XPCollection<securitysystemroleparentroles_securitysystemrolechildroles> securitysystemroleparentroles_securitysystemrolechildroless { get { return GetCollection<securitysystemroleparentroles_securitysystemrolechildroles>("securitysystemroleparentroles_securitysystemrolechildroless"); } }
        [Association(@"securitysystemroleparentroles_securitysystemrolechildrolesReferencessecuritysystemrole1")]
        public XPCollection<securitysystemroleparentroles_securitysystemrolechildroles> securitysystemroleparentroles_securitysystemrolechildroless1 { get { return GetCollection<securitysystemroleparentroles_securitysystemrolechildroles>("securitysystemroleparentroles_securitysystemrolechildroless1"); } }
        [Association(@"securitysystemtypepermissionsobjectReferencessecuritysystemrole")]
        public XPCollection<securitysystemtypepermissionsobject> securitysystemtypepermissionsobjects { get { return GetCollection<securitysystemtypepermissionsobject>("securitysystemtypepermissionsobjects"); } }
        [Association(@"securitysystemuserusers_securitysystemrolerolesReferencessecuritysystemrole")]
        public XPCollection<securitysystemuserusers_securitysystemroleroles> securitysystemuserusers_securitysystemroleroless { get { return GetCollection<securitysystemuserusers_securitysystemroleroles>("securitysystemuserusers_securitysystemroleroless"); } }
        public securitysystemrole(Session session) : base(session) { }
    }

}
