//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXApplication2.Model.j_embuscado_cms
{

    public partial class securitysystemtypepermissionsobject : XPCustomObject
    {
        string fOid;
        [Key]
        [Size(38)]
        public string Oid
        {
            get { return fOid; }
            set { SetPropertyValue<string>("Oid", ref fOid, value); }
        }
        string fTargetType;
        [Size(SizeAttribute.Unlimited)]
        public string TargetType
        {
            get { return fTargetType; }
            set { SetPropertyValue<string>("TargetType", ref fTargetType, value); }
        }
        byte fAllowRead;
        public byte AllowRead
        {
            get { return fAllowRead; }
            set { SetPropertyValue<byte>("AllowRead", ref fAllowRead, value); }
        }
        byte fAllowWrite;
        public byte AllowWrite
        {
            get { return fAllowWrite; }
            set { SetPropertyValue<byte>("AllowWrite", ref fAllowWrite, value); }
        }
        byte fAllowCreate;
        public byte AllowCreate
        {
            get { return fAllowCreate; }
            set { SetPropertyValue<byte>("AllowCreate", ref fAllowCreate, value); }
        }
        byte fAllowDelete;
        public byte AllowDelete
        {
            get { return fAllowDelete; }
            set { SetPropertyValue<byte>("AllowDelete", ref fAllowDelete, value); }
        }
        byte fAllowNavigate;
        public byte AllowNavigate
        {
            get { return fAllowNavigate; }
            set { SetPropertyValue<byte>("AllowNavigate", ref fAllowNavigate, value); }
        }
        securitysystemrole fOwner;
        [Size(38)]
        [Association(@"securitysystemtypepermissionsobjectReferencessecuritysystemrole")]
        public securitysystemrole Owner
        {
            get { return fOwner; }
            set { SetPropertyValue<securitysystemrole>("Owner", ref fOwner, value); }
        }
        [Association(@"securitysystemmemberpermissionsobjectReferencessecuritysystemtypepermissionsobject")]
        public XPCollection<securitysystemmemberpermissionsobject> securitysystemmemberpermissionsobjects { get { return GetCollection<securitysystemmemberpermissionsobject>("securitysystemmemberpermissionsobjects"); } }
        [Association(@"securitysystemobjectpermissionsobjectReferencessecuritysystemtypepermissionsobject")]
        public XPCollection<securitysystemobjectpermissionsobject> securitysystemobjectpermissionsobjects { get { return GetCollection<securitysystemobjectpermissionsobject>("securitysystemobjectpermissionsobjects"); } }
        public securitysystemtypepermissionsobject(Session session) : base(session) { }
    }

}
