//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXApplication2.Model.j_embuscado_cms
{

    public partial class securitysystemroleparentroles_securitysystemrolechildroles : XPObject
    {
        securitysystemrole fChildRoles;
        [Size(38)]
        [Association(@"securitysystemroleparentroles_securitysystemrolechildrolesReferencessecuritysystemrole1")]
        public securitysystemrole ChildRoles
        {
            get { return fChildRoles; }
            set { SetPropertyValue<securitysystemrole>("ChildRoles", ref fChildRoles, value); }
        }
        securitysystemrole fParentRoles;
        [Size(38)]
        [Association(@"securitysystemroleparentroles_securitysystemrolechildrolesReferencessecuritysystemrole")]
        public securitysystemrole ParentRoles
        {
            get { return fParentRoles; }
            set { SetPropertyValue<securitysystemrole>("ParentRoles", ref fParentRoles, value); }
        }
        public securitysystemroleparentroles_securitysystemrolechildroles(Session session) : base(session) { }
    }

}
