//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXApplication2.Model.j_embuscado_cms
{

    public partial class stage : XPObject
    {
        string fDescription;
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        double fWeight;
        public double Weight
        {
            get { return fWeight; }
            set { SetPropertyValue<double>("Weight", ref fWeight, value); }
        }


        [Association(@"case1Referencesstage")]
        public XPCollection<case1> case1s { get { return GetCollection<case1>("case1s"); } }
        [Association(@"statusstatus_stagestageReferencesstage")]
        public XPCollection<statusstatus_stagestage> statusstatus_stagestages { get { return GetCollection<statusstatus_stagestage>("statusstatus_stagestages"); } }
        public stage(Session session) : base(session) { }
    }

}
