//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXApplication2.Model.j_embuscado_cms
{

    public partial class statusstatus_stagestage : XPObject
    {
        stage fStage;
        [Association(@"statusstatus_stagestageReferencesstage")]
        public stage Stage
        {
            get { return fStage; }
            set { SetPropertyValue<stage>("Stage", ref fStage, value); }
        }
        status fStatus;
        [Association(@"statusstatus_stagestageReferencesstatus")]
        public status Status
        {
            get { return fStatus; }
            set { SetPropertyValue<status>("Status", ref fStatus, value); }
        }
        public statusstatus_stagestage(Session session) : base(session) { }
    }

}
