//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXApplication2.Model.j_embuscado_cms
{

    public partial class statusstatus_ruleappliedruleapplied : XPObject
    {
        ruleapplied fRuleApplied;
        [Association(@"statusstatus_ruleappliedruleappliedReferencesruleapplied")]
        public ruleapplied RuleApplied
        {
            get { return fRuleApplied; }
            set { SetPropertyValue<ruleapplied>("RuleApplied", ref fRuleApplied, value); }
        }
        status fStatus;
        [Association(@"statusstatus_ruleappliedruleappliedReferencesstatus")]
        public status Status
        {
            get { return fStatus; }
            set { SetPropertyValue<status>("Status", ref fStatus, value); }
        }
        public statusstatus_ruleappliedruleapplied(Session session) : base(session) { }
    }

}
