//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXApplication2.Model.j_embuscado_cms
{

    public partial class time : XPObject
    {
        string fHour;
        public string Hour
        {
            get { return fHour; }
            set { SetPropertyValue<string>("Hour", ref fHour, value); }
        }
        [Association(@"docketReferencestime")]
        public XPCollection<docket> dockets { get { return GetCollection<docket>("dockets"); } }
        public time(Session session) : base(session) { }
    }

}
