//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DXApplication2.Model.j_embuscado_cms
{

    public partial class typetype_kindkind : XPObject
    {
        kind fKind;
        [Association(@"typetype_kindkindReferenceskind")]
        public kind Kind
        {
            get { return fKind; }
            set { SetPropertyValue<kind>("Kind", ref fKind, value); }
        }
        type fType;
        [Association(@"typetype_kindkindReferencestype")]
        public type Type
        {
            get { return fType; }
            set { SetPropertyValue<type>("Type", ref fType, value); }
        }
        public typetype_kindkind(Session session) : base(session) { }
    }

}
